version: '2.0'
services:
#  S:
#    image: rosetta:v0.2
#    tty: true
#    volumes:
#      - /Users/qizhi.zqz/projects/Rosetta/app/:/app/
#    command:
#      - /bin/bash
  P0:
    image: rosetta:v0.2
    #image: registry.cn-hangzhou.aliyuncs.com/dtunion/morsestf:idash20_SGD
    ports:
      - 7777:7777
      - 5679:5216 # devU 5216=outer port=docker inner port
    tty: true
    volumes:
      - /Users/qizhi.zqz/projects/Rosetta/app/:/app/
    command:
      #/bin/bash -c "cd app && python rosetta_demo.py --party_id=0"
      #- apt-get install gcc
      - /bin/bash
  P1:
    image: rosetta:v0.2
    #image: registry.cn-hangzhou.aliyuncs.com/dtunion/morsestf:idash20_SGD
    ports:
      - 7777:7777
    tty: true
    volumes:
      - /Users/qizhi.zqz/projects/Rosetta/app/:/app/
    command:
      #/bin/bash -c "cd app && python rosetta_demo.py --party_id=1"
      #- apt-get install gcc
      - /bin/bash
  P2:
    image: rosetta:v0.2
    #image: registry.cn-hangzhou.aliyuncs.com/dtunion/morsestf:idash20_SGD
    ports:
      - 7777:7777
    tty: true
    volumes:
      - /Users/qizhi.zqz/projects/Rosetta/app/:/app/
    command:
      #/bin/bash -c "cd app && python rosetta_demo.py --party_id=2"
      #- apt-get install gcc
      - /bin/bash
